### ISSUE TITLE
Is this still an issue with the latest iOS?

### ISSUE THREAD

**Issue by fysteven** [fabb/CollectiveCrash#1]

**Comment by fabb** [comment]
You could just check out the project and try it and write the results here ;-)

**Comment by fysteven** [comment]
I actually tried it just now. The bug didn't happen to me. I was using Xcode Version 10.1 (10B61) and its corresponding iOS 12.1 SDK.

**Comment by fabb** [comment]
Good to hear. My Radar wasn‘t yet closed though.

**Comment by fabb** [comment]
Indeed, in Xcode 10.1 with iOS 12.1 simulator, it seems to work fine. I have installed the 12.0 and 11.4 simulators, and there it still behaves buggy as initially described. I'll update the readme.
